# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-toml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/myint/autoflake
  rev: v2.2.1
  hooks:
    - id: autoflake
      exclude: .*/__init__.py
      args:
        - --in-place
        - --remove-all-unused-imports
        - --expand-star-imports
        - --remove-duplicate-keys
        - --remove-unused-variables

- repo: https://github.com/asottile/pyupgrade
  rev: v3.15.0
  hooks:
  - id: pyupgrade
    args: [--py37-plus]
- repo: https://github.com/psf/black
  rev: 23.12.1
  hooks:
  - id: black

- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.12.0
  hooks:
    - id: reorder-python-imports

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.1.11
  hooks:
    - id: ruff

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.8.0
  hooks:
  - id: mypy
    additional_dependencies:
    - types-python-dateutil
